# @package _global_

fps: 10

env:
  name: pusht
  task: PushT-v0
  image_size: 96
  state_dim: 5
  action_dim: 2
  fps: ${fps}
  episode_length: 300
  gym:
    obs_type: pixels_state
    render_mode: rgb_array
    visualization_width: 384
    visualization_height: 384
    observation_width: 96
    observation_height: 96
    force_sparse: false
    display_cross: false
